# application-dev.yml
# ============================================================
# DEVELOPMENT PROFILE CONFIGURATION
# ============================================================

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/moktob_saas_dev
    username: postgres
    password: T@krim1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.moktob: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: moktobDevSecretKey123456789012345678901234567890

# Development-specific feature flags
features:
  email-sending: false
  payment-processing: false
  audit-logging: true

# CORS configuration for development
cors:
  allowed-origins: http://localhost:3000,http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: Authorization,Content-Type,X-Requested-With