# application.yml
# ============================================================
# DEFAULT CONFIGURATION (applies to all profiles)
# ============================================================

spring:
  application:
    name: MOKTOB
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  datasource:
    username: postgres
    password: T@krim1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false # Best practice to avoid LazyInitializationException
  profiles:
    active: alpha
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: takrimul25@gmail.com
    password: ${MAIL_PASSWORD:missionIslam#01}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8080
  servlet:
    context-path: "/moktob"
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-binding-errors: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.moktob: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: moktobSecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# ============================================================
# NOTE ON ACTIVE PROFILE
# ============================================================
# Do not hardcode profile here. Set it externally:
# 1. Command-line: --spring.profiles.active=alpha
# 2. Environment variable: SPRING_PROFILES_ACTIVE=alpha
# 3. VM option: -Dspring.profiles.active=alpha