# application-alpha.yml
# ============================================================
# ALPHA PROFILE CONFIGURATION
# ============================================================

spring:
  config:
    activate:
      on-profile: alpha  # Modern way to specify a profile in Spring Boot 2.4+
  datasource:
    url: jdbc:postgresql://localhost:5432/moktob_saas
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000   # 10 minutes
      max-lifetime: 1800000  # 30 minutes
      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: update  # Consider using 'validate' in non-dev environments

server:
  port: 8080

jwt:
  secret: moktobSecretKey123456789012345678901234567890
  expiration: 3600000  # 1 hour - shorter for alpha environment

logging:
  level:
    com.moktob: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom alpha-specific configuration
alpha:
  feature-toggles:
    new-user-flow: true
    enhanced-security: false

  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type